alarm[0] = 5; 
global.score = 0
// Wave 2
	global.wave_2_phase = 0; 
	global.wave_2_timer = 0;
// Wave 3
	global.wave_3_phase = 0; 
	global.wave_3_timer = 0;
// Wave 4
	global.wave_4_phase = 0; 
	global.wave_4_timer = 0;
// Wave 5
	global.wave_5_phase = 0; 
	global.wave_5_timer = 0;
// Wave 6
	global.wave_6_phase = 0; 
	global.wave_6_timer = 0;